### ISSUE TITLE
peer code review

### ISSUE THREAD

**Issue by sjdev2212** [lu-jim/to-do#13]
Hi Luis. This is an awesome job!.
Here are some suggestions...
Try using simpler mocking functions to test the functionality of said functions.
Consider exporting an array in your test file to mock the local storage and user inputs.

**Comment by Medini-Rajendra** [comment]
Hi Luis. Great job in implementing unit tests on your project. After reviewing the code, I found that it is always better to separate the functions and do mock tests on it, rather than using the functions from your original file itself. This would be a simpler way of implementing mock functions and test them.

Good Luck!!! Keep Going.

**Comment by lu-jim** [comment]
Thanks for the feedback guys! With your advice, we were able to make the testing work.
